config/routes.rb
Rails.application.routes.draw do
 
 post '/final' => 'orders#final'

  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
 
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'
  
  get '/myorders' => 'store#myorders'
  
  post '/search' => 'store#search'

  resources :orders
  devise_for :users, :controllers => { registrations: 'user/registrations' }
  root :to => 'store#index', :via => :get
  
  match '/store/album/:id' => 'store#show', :as => :store_album, :via => :get
  match '/store/genre/:id' => 'store#genre', :as => :store_genre, :via => :get
  match '/store/artist/:id' => 'store#artist', :as => :store_artist, :via => :get
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  get '/store/genres', to: 'store#genrelayout'
  get '/store/albums', to: 'store#albumlayout'
  get '/store/artists', to: 'store#artistlayout'
  
  
  resources :orders, :path => "admin/orders"
  resources :artists, :path => "admin/artists"
  resources :genres, :path => "admin/genres"
  resources :albums, :path => "admin/albums"
  resources :users, :path => "admin/users"
  get '/admin', to: 'admin#admin'

end

app/models/genre.rb
class Genre < ActiveRecord::Base
  
  has_many :albums
  
  has_attached_file :image, styles: { large: "1000x1000>", medium: "600x600>", thumb: "200x200>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_filter :verify_is_admin


  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
    @genres = Genre.order(:name)
  end

  # GET /genres/1/edit
  def edit
    @genres = Genre.order(:name)
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:name, :description, :image)
    end
    
      private
  
    def verify_is_admin
      (current_user.nil?) ? redirect_to(new_user_session_path) : (redirect_to(new_user_session_path) unless current_user.admin?)
    end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_for @genre, html: { multipart: true } do |f| %>
  <% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% @genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/genres/_genre.html.erb
<% if current_page?(action: 'genrelayout') %>
<div class="genre-result">
  <div class="image">
    <%= link_to (image_tag genre.image.url(:medium), :class => "genre-image", :alt => genre.name), store_genre_path(genre), :title => genre.name %>
  </div>
  <h2><%= link_to genre.name, store_genre_path(genre), :title => genre.name %></h2>
</div>


<%else%>
<section class="genre">
<% if genre.image %>
<div class="genre-cover-image">
    <%=  image_tag genre.image.url(:large) %>
</div>
<% end %>

<h2><%= genre.name %></h2>

<div class "description">
    <%= genre.description %>
</div>

<p><strong>Albums:</strong></p>
  <% genre.albums.each do |album| %>
    <div class="album-result discog">
      <div class="image">   
        <%= link_to  (image_tag album.image.url(:medium), :class => "album-image slider-image", :alt => album.name), store_album_path(album), :title => album.name  %>
      </div> 
      <div class="info">
        <h2><%= link_to album.name, store_album_path(album) %></h2>
        <p class="price"><%= number_to_currency album.price, unit:"€" %></p>
      </div>
    </div>
  <% end %>
  <div style="clear:both"></div>
</section>
<% end %>

app/views/genres/edit.html.erb
<div class="admin edit-genre inner">
<h1>Edit a Genre</h1>
<p><%= link_to "Dashboard", admin_path %></p>
<%= render 'form' %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>
</div>

app/views/genres/index.html.erb
<div class="admin show-genre inner">
  <h1>Admin Dashboard, Welcome <%= current_user.name %></h1>
<ul class="admin-buttons">
  <li><%= link_to "Dashboard", admin_path, :class => "fa fa-tachometer", :id => "button", :title => "View Dashboard" %></li>
  <li><%= link_to 'Artists', artists_path, :class => "fa fa-microphone", :id => "button", :title => "View Artists"  %></li>
  <li><%= link_to 'Genres', genres_path, :class => "fa fa-th", :id => "button", :title => "View Genres"  %></li>
  <li><%= link_to 'Albums', albums_path, :class => "fa fa-music", :id => "button", :title => "View Albums"  %></li>
  <li><%= link_to 'Users', users_path, :class => "fa fa-users", :id => "button", :title => "View Users"  %></li>
  <li><%= link_to 'Orders', orders_path, :class => "fa fa-cart-arrow-down", :id => "button", :title => "View Orders"  %></li>
</ul>
<div style="clear:both;"></div>
<p id="notice"><%= notice %></p>

<h1>Listing All Genres</h1>
<%= link_to 'New Genre', new_genre_path, :class => "fa fa-plus", :id => "button", :title => "New Genre" %>
<div id="no-more-tables">
<table>
  <thead>
    <tr>
      <th class="numeric">Name</th>
      <th class="numeric">Description</th>
      <th class="numeric" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td data-title="Name" class="numeric"><%= genre.name %></td>
        <td data-title="Description" class="numeric"><%= genre.description %></td>
        <td class="numeric"><%= link_to 'Show', genre, :class => "fa fa-eye", :id => "button", :title => "View Genre"  %></td>
        <td class="numeric"><%= link_to 'Edit', edit_genre_path(genre), :class => "fa fa-pencil", :id => "button", :title => "Edit Genre"  %></td>
        <td class="numeric"><%= link_to 'Delete', genre, method: :delete, data: { confirm: 'Are you sure?' }, :class => "fa fa-trash-o", :id => "button", :title => "Delete Genre" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Genre', new_genre_path, :class => "fa fa-plus", :id => "button", :title => "New Genre" %>
</div>

app/views/genres/new.html.erb
<div class="admin new-genre inner">
<h1>New Genre</h1>
<p><%= link_to "Dashboard", admin_path %></p>
<%= render 'form' %>

<%= link_to 'Back', genres_path %>
</div>

app/views/genres/show.html.erb
<div class="admin show-genre inner">
<p><%= link_to "Dashboard", admin_path %></p>
<p id="notice"><%= notice %></p>

<% if @genre.image %>
<div>
    <%=  image_tag @genre.image.url(:medium) %>
</div>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @genre.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @genre.description %>
</p>

<p><strong>Albums:</strong></p>
  
   <% @genre.albums.each do |album| %>
        <div class="album-result discog">
          <div class="image">   
            <%= link_to  (image_tag album.image.url(:medium), :class => "album-image slider-image", :alt => album.name), album, :title => album.name  %>
          </div> 
          <div class="info">
            <h2><%= link_to album.name, album %></h2>
            <p class="price"><%= number_to_currency album.price, unit:"€" %></p>
          </div>
        </div>
    <% end %>
<div style="clear:both"></div>

   

<%= link_to 'Edit', edit_genre_path(@genre) %> |
<%= link_to 'Back', genres_path %>
</div>