config/routes.rb
Rails.application.routes.draw do
 
 post '/final' => 'orders#final'

  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
 
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'
  
  get '/myorders' => 'store#myorders'
  
  post '/search' => 'store#search'

  resources :orders
  devise_for :users, :controllers => { registrations: 'user/registrations' }
  root :to => 'store#index', :via => :get
  
  match '/store/album/:id' => 'store#show', :as => :store_album, :via => :get
  match '/store/genre/:id' => 'store#genre', :as => :store_genre, :via => :get
  match '/store/artist/:id' => 'store#artist', :as => :store_artist, :via => :get
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  get '/store/genres', to: 'store#genrelayout'
  get '/store/albums', to: 'store#albumlayout'
  get '/store/artists', to: 'store#artistlayout'
  
  
  resources :orders, :path => "admin/orders"
  resources :artists, :path => "admin/artists"
  resources :genres, :path => "admin/genres"
  resources :albums, :path => "admin/albums"
  resources :users, :path => "admin/users"
  get '/admin', to: 'admin#admin'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  
  has_many :albums
  
  has_attached_file :image, styles: { large: "1920x1920>", medium: "450x450>", thumb: "200x200>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  
  
  before_filter :verify_is_admin
  
  
  
  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
    @artists = Artist.order(:name)
  end

  # GET /artists/1/edit
  def edit
     @artists = Artist.order(:name)
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :description, :image, :featured)
    end
    
    
     private
  
    def verify_is_admin
      (current_user.nil?) ? redirect_to(new_user_session_path) : (redirect_to(new_user_session_path) unless current_user.admin?)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_artist.html.erb
<% if current_page?(action: 'artistlayout') %>
    <div class="artist-result">
      <div class="image">
        <span><%= link_to (image_tag artist.image.url(:medium), :class => "artist-image", :alt => artist.name), store_artist_path(artist), :title => artist.name %></span>
      </div>
      <h2><%= link_to artist.name, store_artist_path(artist), :title => artist.name %></h2>
    </div>

<% elsif current_page?(root_path) %>
    
    <div class="swiper-slide">
      <%=(image_tag artist.image.url(:large), :class => "artist-image", :alt => artist.name) %>
      <h2><%= artist.name %></h2>
      <p><%= artist.description.truncate(250) %></p>
 			<button><%= link_to "VIEW MORE", store_artist_path(artist), :title => artist.name %></button>
    </div>   
    
    
<% else %>

  <section class="artist">
     
      <div class="image main">
          <%=(image_tag artist.image.url(:large), :class => "artist-image", :alt => artist.name) %>
      </div>
    <div class="artist-overlay">
      <h1><%= artist.name%></h1>
      <div class="description">
        <%= @artist.description %>
      </div>
      <div class="discography">
        <p><strong>Albums:</strong></p>
          <% @artist.albums.each do |album| %>
            <div class="album-result discog">
             <div class="image">   
              <%= link_to  (image_tag album.image.url(:medium), :class => "album-image slider-image", :alt => album.name), store_album_path(album), :title => album.name  %>
              </div> 
              <div class="info">
                  <h2><%= link_to album.name, store_album_path(album) %></h2>
                  <p class="price"><%= number_to_currency album.price, unit:"€" %></p>
                  
              </div>
            </div>
       
          <% end %>
        
        <div style="clear:both"></div>
       </div>
     </div>
  </section>



    
<%end%>

app/views/artists/_form.html.erb
<%= form_for @artist, html: { multipart: true } do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <h2>Featured Artist</h2>
  <p><i>Highlight the Artist on the homepage</i></p>
  <div class="field">
    <%= f.label :featured %> <br />
    <%= f.select :featured, [['No', false], ['Yes', true]] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<div class="admin edit inner">
<h1>Editing Artist</h1>
<p><%= link_to "Dashboard", admin_path %></p>
<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>
</div>

app/views/artists/index.html.erb
<div class="admin artists inner">
  <h1>Admin Dashboard, Welcome <%= current_user.name %></h1>
<ul class="admin-buttons">
  <li><%= link_to "Dashboard", admin_path, :class => "fa fa-tachometer", :id => "button", :title => "View Dashboard" %></li>
  <li><%= link_to 'Artists', artists_path, :class => "fa fa-microphone", :id => "button", :title => "View Artists"  %></li>
  <li><%= link_to 'Genres', genres_path, :class => "fa fa-th", :id => "button", :title => "View Genres"  %></li>
  <li><%= link_to 'Albums', albums_path, :class => "fa fa-music", :id => "button", :title => "View Albums"  %></li>
  <li><%= link_to 'Users', users_path, :class => "fa fa-users", :id => "button", :title => "View Users"  %></li>
  <li><%= link_to 'Orders', orders_path, :class => "fa fa-cart-arrow-down", :id => "button", :title => "View Orders"  %></li>
</ul>
<div style="clear:both;"></div>
<p id="notice"><%= notice %></p>
<h1>Listing All Artists</h1>
<%= link_to 'New Artist', new_artist_path, :class => "fa fa-plus", :id => "button", :title => "New Artist" %>
<div id="no-more-tables">
<table>
  <thead>
    <tr>
      <th class="numeric">Name</th>
      <th class="numeric">Featured</th>
      <th class="numeric" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td data-title="Name" class="numeric"><%= artist.name %></td>
        <td data-title="Featured" class="numeric"><%= artist.featured? %></td>
        <td  class="numeric"><%= link_to 'Show', artist, :class => "fa fa-eye", :id => "button", :title => "View Artist"  %></td>
        <td  class="numeric"><%= link_to 'Edit', edit_artist_path(artist), :class => "fa fa-pencil", :id => "button", :title => "Edit Artist"  %></td>
        <td  class="numeric"><%= link_to 'Delete', artist, method: :delete, data: { confirm: 'Are you sure?' }, :class => "fa fa-trash-o", :id => "button", :title => "Delete Artist"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Artist', new_artist_path, :class => "fa fa-plus", :id => "button", :title => "New Artist" %>
</div>

app/views/artists/new.html.erb
<div class="admin new-artist inner">
<h1>New Artist</h1>
<p><%= link_to "Dashboard", admin_path %></p>
<%= render 'form' %>

<%= link_to 'Back', artists_path %>
</div>

app/views/artists/show.html.erb
<div class="admin show-artist inner">
<p id="notice"><%= notice %></p>
<p><%= link_to "Dashboard", admin_path %></p>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>
<% if @artist.image %>
<div>
    <%=  image_tag @artist.image.url(:medium) %>
</div>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @artist.description %>
</p>

<p><strong>Albums:</strong></p>
  <% @artist.albums.each do |album| %>
    <div class="album-result discog">
        <div class="image">   
            <%= link_to  (image_tag album.image.url(:medium), :class => "album-image slider-image", :alt => album.name), album, :title => album.name  %>
        </div> 
        <div class="info">
          <h2><%= link_to album.name, album %></h2>
          <p class="price"><%= number_to_currency album.price, unit:"€" %></p>
        </div>
    </div>
  <% end %>
<div style="clear:both"></div>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>
</div>