config/routes.rb
Rails.application.routes.draw do
 
 post '/final' => 'orders#final'

  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
 
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'
  
  get '/myorders' => 'store#myorders'
  
  post '/search' => 'store#search'

  resources :orders
  devise_for :users, :controllers => { registrations: 'user/registrations' }
  root :to => 'store#index', :via => :get
  
  match '/store/album/:id' => 'store#show', :as => :store_album, :via => :get
  match '/store/genre/:id' => 'store#genre', :as => :store_genre, :via => :get
  match '/store/artist/:id' => 'store#artist', :as => :store_artist, :via => :get
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  get '/store/genres', to: 'store#genrelayout'
  get '/store/albums', to: 'store#albumlayout'
  get '/store/artists', to: 'store#artistlayout'
  
  
  resources :orders, :path => "admin/orders"
  resources :artists, :path => "admin/artists"
  resources :genres, :path => "admin/genres"
  resources :albums, :path => "admin/albums"
  resources :users, :path => "admin/users"
  get '/admin', to: 'admin#admin'

end

app/models/album.rb
class Album < ActiveRecord::Base
  
  belongs_to :genre
  belongs_to :artist
  has_many :order_items
  
  # validates :name, :description, :price, :presence => true
  #validates :price, numericality => true
  
  has_attached_file :image, styles: { large: "900x900>", medium: "450x450>", thumb: "200x200>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  
  
  
end
 

app/models/artist.rb
class Artist < ActiveRecord::Base
  
  has_many :albums
  
  has_attached_file :image, styles: { large: "1920x1920>", medium: "450x450>", thumb: "200x200>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  
  has_many :albums
  
  has_attached_file :image, styles: { large: "1000x1000>", medium: "600x600>", thumb: "200x200>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items
  belongs_to :user
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

  def final
    self.order_status_id = 2
    self.user_id = current_user.id
    @userid = current_user.id
    @order.user_id = current_user.id
    #@order_items = destroy
    order.save
    
  end
  
  
#    validates :name, :email, presence: true
#    serialize :notification_params, Hash
#     def paypal_url(return_path)
#     values = {
#      business: "johnny.p.norton-facilitator@gmail.com",
#      cmd: "_xclick",
#      upload: 1,
#      return: "#{Rails.application.secrets.app_host}#{return_path}",
#     invoice: id,
#      amount: order.price,
#     item_album: album.name,
#      album_number: album.id,
#      quantity: '1',
#      notify_url: "#{Rails.application.secrets.app_host}/hook"
#    }
#    "#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" + values.to_query
#  end
  

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :album
  belongs_to :order
  belongs_to :user

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      album.price
    end
  end
  
  def total_price
    unit_price * quantity
  end


  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  
  
  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
    self[:album_id] = album_id
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :order_items
  has_many :orders

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
#class AdminController < ActionController::Base
 before_filter :verify_is_admin


  def admin
  end

  private
  
  def verify_is_admin
    (current_user.nil?) ? redirect_to(new_user_session_path) : (redirect_to(new_user_session_path) unless current_user.admin?)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  
  before_action :authenticate_user!
  
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @albums = Album.order(:id)
    @genres = Genre.order(:name)
    @artists = Artist.order(:name)
    
  end #automatically load: app/views/store/index.html.erb

  def show
    
    @album = Album.find(params[:id])
    @order_item = current_order.order_items.new
  end #automatically load: app/views/store/show.html.erb
  
  def myorders
    @orders = current_user.orders
    @order_items = OrderItem.all
    
  end
  
  def genre
    @genre = Genre.find(params[:id])
    @genres = Genre.order(:name)
  end #automatically load: app/views/store/genre.html.erb
  
  def artist
    @artist = Artist.find(params[:id])
  end 
  
  def genrelayout
    @genres = Genre.order(:name)
  end 
  
  def albumlayout
    @albums = Album.order(:name)
  end 
  
  def artistlayout
    @artists = Artist.order(:name)
  end 
  
  # SEARCH
   def search
     @search_term = params[:q]
     st = "%#{params[:q]}%"
     @albums = Album.where("Name ILIKE ? or Description ILIKE ?", st, st)
    
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @albums }
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :verify_is_admin
  
  
  
    def verify_is_admin
      (current_user.nil?) ? redirect_to(new_user_session_path) : (redirect_to(new_user_session_path) unless current_user.admin?)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_adminnav.html..erb
<ul class="admin-buttons">
  <li><%= link_to "Dashboard", admin_path, :class => "fa fa-tachometer", :id => "button", :title => "View Dashboard" %></li>
  <li><%= link_to 'Artists', artists_path, :class => "fa fa-microphone", :id => "button", :title => "View Artists"  %></li>
  <li><%= link_to 'Genres', genres_path, :class => "fa fa-th", :id => "button", :title => "View Genres"  %></li>
  <li><%= link_to 'Albums', albums_path, :class => "fa fa-music", :id => "button", :title => "View Albums"  %></li>
  <li><%= link_to 'Users', users_path, :class => "fa fa-users", :id => "button", :title => "View Users"  %></li>
  <li><%= link_to 'Orders', orders_path, :class => "fa fa-cart-arrow-down", :id => "button", :title => "View Orders"  %></li>
</ul>
<div style="clear:both;"></div>

app/views/admin/admin.html.erb
<div class="admin dashboard inner">
  <h1>Admin Dashboard, </br>Welcome <%= current_user.name %></h1>
  <ul class="admin-buttons">
    <li><%= link_to "Dashboard", admin_path, :class => "fa fa-tachometer", :id => "button", :title => "View Dashboard" %></li>
    <li><%= link_to 'Artists', artists_path, :class => "fa fa-microphone", :id => "button", :title => "View Artists"  %></li>
    <li><%= link_to 'Genres', genres_path, :class => "fa fa-th", :id => "button", :title => "View Genres"  %></li>
    <li><%= link_to 'Albums', albums_path, :class => "fa fa-music", :id => "button", :title => "View Albums"  %></li>
    <li><%= link_to 'Users', users_path, :class => "fa fa-users", :id => "button", :title => "View Users"  %></li>
    <li><%= link_to 'Orders', orders_path, :class => "fa fa-cart-arrow-down", :id => "button", :title => "View Orders"  %></li>
  </ul>
<div style="clear:both;"></div>
</div>

app/views/layouts/_cart_info.html.erb
<%= link_to "You have #{current_order.order_items.size} items in your cart. Total cost, #{number_to_currency current_order.subtotal}", cart_path, class: "btn btn-link nav-cart" %>

app/views/layouts/_cart_text.html.erb
<div class="cart-amount"><%= link_to "#{current_order.order_items.size}", cart_path, class: "cart-quantity", :title => "Cart" %></div>

app/views/layouts/application.html.0.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Retro Records: Classic Vinyl Records</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    
  	<!-- Fonts and Font Awesome -->
  	
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Permanent+Marker"/>
	
  	<!-- Javascript -->
  	<script src="https://code.jquery.com/jquery-2.1.4.js"></script>
  
</head>
<body>

<nav id="menu">
     
	<ul class="menu-section-list">
    	<li><i class="fa fa-home"></i><%= link_to 'Home', root_path, :title => "Home" %></li>
        <li><i class="fa fa-music"></i><%= link_to 'Artists', store_artists_path, :title => "Artists" %></li>
        <li><i class="fa fa-th-large"></i><%= link_to 'Genres', store_genres_path, :title => "Genres" %></li>
        <li><i class="fa fa-headphones"></i><%= link_to 'Albums', store_albums_path, :title => "Albums" %></li>
    <% if user_signed_in? %>
        <li><i class="fa fa-user"></i><%= link_to "Profile", edit_user_registration_path, :title => "Profile" %></li>
        <li><i class="fa fa-shopping-cart"></i> <%= link_to "My Orders", myorders_path, :title => "My Orders" %></li>
        <li><i class="fa fa-sign-out"></i><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
    <% else %>
        <li><i class="fa fa-sign-in"></i><%= link_to('Login', new_user_session_path)  %></li>  
        <li><i class="fa fa-user"></i><%= link_to "Register", new_user_registration_path, :title => "Register" %></li>
    <% end %>
        <li class="cart-info"><i class="fa fa-shopping-cart"></i> <%= render 'layouts/cart_info' %></li>
    <% if user_signed_in? && current_user.admin %>
          <li><i class="fa fa-unlock-alt"></i></li>
          <li><i class="fa fa-cogs"></i><%= link_to "Dashboard", admin_path %></li>
          <li><i class="fa fa-microphone"></i><%= link_to 'Artists', artists_path %></li>
          <li><i class="fa fa-th"></i><%= link_to 'Genres', genres_path %></li>
          <li><i class="fa fa-music"></i><%= link_to 'Albums', albums_path %></li>
          <li><i class="fa fa-users"></i><%= link_to 'All Users', users_path %></li>
          <li><i class="fa fa-credit-card"></i><%= link_to 'Orders', orders_path %></li>
    <% end %>
    </ul>
</nav>

<div id="header">
    	      <div id="toggle-btn">
        	    <button id="menu-btn" class="toggle-button"><i class="fa fa-bars"></i></button>
            </div>
             <div class="user-menu left">
               <ul>
                    <li class="home-button"><%= link_to "Home", root_path, :class => "fa fa-home", :title => "Home" %></li>
                    <li class="logo-button"><%= link_to "Home", root_path, :class => "site-logo", :title => "Home" %></li>
                    
                </ul>
            </div>
            <div class="header-search">
              <%= render :partial => 'store/search' %>
            </div>
            <div class="user-menu right">
               <ul>
                   <li class="text-nav"><%= link_to 'Albums', store_albums_path, :title => "Albums" %></li>
                   <li class="text-nav"><%= link_to 'Artists', store_artists_path, :title => "Artists" %></li>
                   <li class="text-nav"><%= link_to 'Genres', store_genres_path, :title => "Genres" %></li>
                    <li class="cart-button"><%= link_to "Cart", cart_path, :class => "fa fa-shopping-cart", :title => "My Cart" %></li>
                    <li class="cart-text mini-cart"><%= render 'layouts/cart_text' %></li>
                    <% if user_signed_in? %>
                    <li class="profile-button"><%= link_to "Profile", edit_user_registration_path, :class => "fa fa-user", :title => "My Account" %></li>
                    <% else %>
                    <li class="profile-button"><%= link_to('Login', new_user_session_path, :class => "fa fa-user", :title => "Login") %></li>  
                    <% end %>
                </ul>
            </div>
            <div style="clear:both;"></div>
</div>
	
<main id="panel">
	   
	
      <div id="main-container" class="main-container">
          <%= yield %>
          <p class="notice" id="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
         
      </div>
      <div class="footer" >
		    <div class="container">
  			<div class="row">
  				<div class="footer_container">
                    <div class="footer-cols">
                    	<h3>Browse our categories...</h3>
                    	<div class="footer-col">
                            <ul>
                                <li><a href="#">Alternative/Indie</a></li>
                                <li><a href="#">Blues</a></li>
                                <li><a href="#">Classical</a></li>
                                <li><a href="#">Country</a></li>
                                <li><a href="#">Dance/Electronic</a></li>
                            </ul>
                      </div>
                        
                      
                        <div class="footer-col">
                            <ul>
                                <li><a href="#">Folk</a></li>
                                <li><a href="#">Hip-Hop/Rap</a></li>
                                <li><a href="#">Jazz</a></li>
                                <li><a href="#">Metal</a></li>
                                <li><a href="#">Pop</a></li>
                            </ul>
                        </div>
                        <div class="footer-col">
                            <ul>
                                <li><a href="#">R&amp;B/Soul</a></li>
                                <li><a href="#">Regge</a></li>
                                <li><a href="#">Rock</a></li>
                                <li><a href="#">Soundtracks</a></li>
                                <li><a href="#">Vocal/Easy Listening</a></li>
                            </ul>
                        </div>
                        <div style="clear:both"></div>
					</div>
                    <div class="height30"></div>
                    <img class="footer-logo" src="http://retro-records.s3.amazonaws.com/template/retro-records-logo.png" alt="Retro Records"/>
				</div>
                <div class="footer_bottom_content">
                	<span>Copyright © 2016 Retro Records - Website by Team Burrito</span>
                </div>
			
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	</div>
</main>



<!-- Initialize Slideout Menu -->
    <script>
      $( document ).ready(function() {
        
        var slideout = new Slideout({
        'panel': document.getElementById('panel'),
        'menu': document.getElementById('menu'),
        'padding': 250,
        'tolerance': 70,
        'touch': false
        });
      
        // Toggle button
        document.querySelector('.toggle-button').addEventListener('click', function() {
        slideout.toggle();
        });
      });
      
      $( document ).ready(function() {
    
          $(window).scrollTop(0);
      });
      
      
    $ ( document ).ready(function() {
         
      var notice = document.getElementById("notice").length;
      
         if($.trim($("#notice").html())!=''){
    
              $("#notice").fadeIn('fast').delay(3000).fadeOut('slow');
              
          }
        
      });
        
        
        
        
    </script>
	

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Retro Records: Classic Vinyl Records</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    
  	<!-- Fonts and Font Awesome -->
  	
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Permanent+Marker"/>
	
  	<!-- Javascript -->
  	<!--<script src="https://code.jquery.com/jquery-2.1.4.js"></script>-->
  
</head>
<body>

<nav id="menu">
     <img class="logo" src="http://retro-records.s3.amazonaws.com/template/retro-records-logo.png" alt="Retro Records"/>
     
	<ul class="menu-section-list">
    	<li><i class="fa fa-home"></i><%= link_to 'Home', root_path, :title => "Home" %></li>
        <li><i class="fa fa-music"></i><%= link_to 'Artists', store_artists_path, :title => "Artists" %></li>
        <li><i class="fa fa-th-large"></i><%= link_to 'Genres', store_genres_path, :title => "Genres" %></li>
        <li><i class="fa fa-headphones"></i><%= link_to 'Albums', store_albums_path, :title => "Albums" %></li>
    <% if user_signed_in? %>
        <li><i class="fa fa-user"></i><%= link_to "Profile", edit_user_registration_path, :title => "Profile" %></li>
         <li><i class="fa fa-shopping-cart"></i> <%= link_to "My Orders", myorders_path, :title => "My Orders" %></li>
        <li><i class="fa fa-sign-out"></i><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
    <% else %>
        <li><i class="fa fa-sign-in"></i><%= link_to('Login', new_user_session_path)  %></li>  
        <li><i class="fa fa-user"></i><%= link_to "Register", new_user_registration_path, :title => "Register" %></li>
    <% end %>
        <li class="cart-info"><i class="fa fa-shopping-cart"></i> <%= render 'layouts/cart_info' %></li>
    <% if user_signed_in? && current_user.admin %>
          <li><i class="fa fa-unlock-alt"></i></li>
          <li><i class="fa fa-cogs"></i><%= link_to "Dashboard", admin_path %></li>
          <li><i class="fa fa-microphone"></i><%= link_to 'Artists', artists_path %></li>
          <li><i class="fa fa-th"></i><%= link_to 'Genres', genres_path %></li>
          <li><i class="fa fa-music"></i><%= link_to 'Albums', albums_path %></li>
          <li><i class="fa fa-users"></i><%= link_to 'All Users', users_path %></li>
          <li><i class="fa fa-credit-card"></i><%= link_to 'Orders', orders_path %></li>
    <% end %>
    </ul>
</nav>

<main id="panel">
	<div id="header">
    	      <div id="toggle-btn">
        	    <button id="menu-btn" class="toggle-button"><i class="fa fa-bars"></i></button>
            </div>
             <div class="user-menu left">
               <ul>
                    <li class="home-button"><%= link_to "Home", root_path, :class => "fa fa-home", :title => "Home" %></li>
                    <li class="logo-button"><%= link_to "Home", root_path, :class => "site-logo", :title => "Home" %></li>
                    
                </ul>
            </div>
            <div class="header-search">
              <%= render :partial => 'store/search' %>
            </div>
            <div class="user-menu right">
               <ul>
                   <li class="text-nav"><%= link_to 'Albums', store_albums_path, :title => "Albums" %></li>
                   <li class="text-nav"><%= link_to 'Artists', store_artists_path, :title => "Artists" %></li>
                   <li class="text-nav"><%= link_to 'Genres', store_genres_path, :title => "Genres" %></li>
                    <li class="cart-button"><%= link_to "Cart", cart_path, :class => "fa fa-shopping-cart", :title => "My Cart" %></li>
                    <li class="cart-text mini-cart"><%= render 'layouts/cart_text' %></li>
                    <% if user_signed_in? %>
                    <li class="profile-button"><%= link_to "Profile", edit_user_registration_path, :class => "fa fa-user", :title => "My Account" %></li>
                    <% else %>
                    <li class="profile-button"><%= link_to('Login', new_user_session_path, :class => "fa fa-user", :title => "Login") %></li>  
                    <% end %>
                </ul>
            </div>
            <div style="clear:both;"></div>
	</div>   
	
      <div id="main-container" class="main-container">
          <%= yield %>
          <p class="notice" id="notice"><%= notice %></p>
          <p class="alert" id="alert"><%= alert %></p>
         
      </div>
      <div class="footer" >
		    <div class="container">
  			<div class="row">
  				<div class="footer_container">
                    
                    <div class="height30"></div>
                    <img class="footer-logo" src="http://retro-records.s3.amazonaws.com/template/retro-records-logo.png" alt="Retro Records"/>
				</div>
                <div class="footer_bottom_content">
                	<span>Copyright © 2016 Retro Records - Website by Team Burrito</span>
                </div>
			
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	</div>
</main>



<!-- Initialize Slideout Menu -->
    <script>
      $( document ).ready(function() {
        
        var slideout = new Slideout({
        'panel': document.getElementById('panel'),
        'menu': document.getElementById('menu'),
        'padding': 250,
        'tolerance': 70,
        'touch': false
        });
      
        // Toggle button
        document.querySelector('.toggle-button').addEventListener('click', function() {
        slideout.toggle();
        });
      });
      
      $( document ).ready(function() {
    
          $(window).scrollTop(0);
      });
      
      
    $ ( document ).ready(function() {
         
      var notice = document.getElementById("notice").length;
      
         if($.trim($("#notice").html())!=''){
    
              $("#notice").fadeIn('fast').delay(3000).fadeOut('slow');
              
          }
          var notice = document.getElementById("alert").length;
      
         if($.trim($("#alert").html())!=''){
    
              $("#alert").fadeIn('fast').delay(3000).fadeOut('slow');
              
          }
        
      });
        
        
        
        
    </script>
	

</body>
</html>