config/routes.rb
Rails.application.routes.draw do
 
 post '/final' => 'orders#final'

  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
 
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'
  
  get '/myorders' => 'store#myorders'
  
  post '/search' => 'store#search'

  resources :orders
  devise_for :users, :controllers => { registrations: 'user/registrations' }
  root :to => 'store#index', :via => :get
  
  match '/store/album/:id' => 'store#show', :as => :store_album, :via => :get
  match '/store/genre/:id' => 'store#genre', :as => :store_genre, :via => :get
  match '/store/artist/:id' => 'store#artist', :as => :store_artist, :via => :get
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  get '/store/genres', to: 'store#genrelayout'
  get '/store/albums', to: 'store#albumlayout'
  get '/store/artists', to: 'store#artistlayout'
  
  
  resources :orders, :path => "admin/orders"
  resources :artists, :path => "admin/artists"
  resources :genres, :path => "admin/genres"
  resources :albums, :path => "admin/albums"
  resources :users, :path => "admin/users"
  get '/admin', to: 'admin#admin'

end

app/models/album.rb
class Album < ActiveRecord::Base
  
  belongs_to :genre
  belongs_to :artist
  has_many :order_items
  
  # validates :name, :description, :price, :presence => true
  #validates :price, numericality => true
  
  has_attached_file :image, styles: { large: "900x900>", medium: "450x450>", thumb: "200x200>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  
  
  
end
 

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
   before_filter :verify_is_admin
 
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
    @order_item = current_order.order_items.new
    @orders = Order.all
  end
  # GET /albums/1
  # GET /albums/1.json
  def show
    @order_item = current_order.order_items.new
  end

  # GET /albums/new
  def new
    @album = Album.new
    @genres = Genre.order(:name)
    @artists = Artist.order(:name)
  end

  # GET /albums/1/edit
  def edit
     @genres = Genre.order(:name)
     @artists = Artist.order(:name)
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:name, :description, :price, :year, :genre_id, :artist_id, :image, :featured)
    end
  
  private
  
    def verify_is_admin
      (current_user.nil?) ? redirect_to(new_user_session_path) : (redirect_to(new_user_session_path) unless current_user.admin?)
    end
  end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_album.html.erb
<% if homepage %>
    <div class="swiper-slide">
        <%= link_to  (image_tag album.image.url(:medium), :class => "album-image slider-image", :alt => album.name), store_album_path(album), :title => album.name  %>
    </div> 
    
<% elsif album_listings %>
    <div class="album-result">
        <div class="image">   
            <%= link_to  (image_tag album.image.url(:medium), :class => "album-image slider-image", :alt => album.name), store_album_path(album), :title => album.name  %>
        </div> 
        <div class="info">
            <h2><%= link_to album.name, store_album_path(album) %></h2>
            <p class="price"><%= number_to_currency album.price, unit:"€" %></p>
        </div>
    </div>

<% else %>
    <section class="album">
            <% if album.image %>
                <div class="album-image">
                        <%= image_tag album.image.url(:medium), :class => "album-image", :alt => album.name%>
                </div>
            <% end %>
           
            <div class="album-details">
                <h2><%= album.name %></h2>
                <p class="name">
                        <strong>Artist:</strong> <%= album.artist.name %>
                </p>
                <p class="price">
                        <strong>Genre:</strong> <%= album.genre.name %>
                </p>
                <p class="price">
                     <strong>Price:</strong> <%= number_to_currency album.price, unit:"€" %>
                </p>
                <p class "description">
                     <strong>Description:</strong> <%= album.description %>
                </p>
                <p class "year">
                     <strong>Year:</strong> <%= album.year %>
                </p>
            
        
                <%= form_for order_item, remote: true do |f| %>
                  <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency album.price %></span></h4>
                    <div class="input-group">
                      <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
                      <div class="input-group-btn">
                        <%= f.hidden_field :album_id, value: album.id %>
                        <%= f.submit "Add to Cart", class: "add-to-cart" %>
                      </div>
                    </div>
                <% end %>
           </div>
            
    </section>
    <div class="other-titles">
   
    </div>
 
<div style="clear:both"></div>

<%end%>

app/views/albums/_form.html.erb
<%= form_for @album, html: { multipart: true } do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :genre_id %><br>
    <%= f.collection_select :genre_id, @genres, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :artist_id %><br>
    <%= f.collection_select :artist_id, @artists, :id, :name %>
  </div>
  <h2>Featured Album</h2>
  <p><i>Highlight the Album as featured on the homepage.</i></p>
  <div class="field">
    <%= f.label :featured %> <br />
    <%= f.select :featured, [['No', false], ['Yes', true]] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<div class="admin edit inner">
<h1>Editing Album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>
</div>

app/views/albums/index.html.erb
<div class="admin list-albums inner">
<h1>Admin Dashboard, Welcome <%= current_user.name %></h1>
<ul class="admin-buttons">
  <li><%= link_to "Dashboard", admin_path, :class => "fa fa-tachometer", :id => "button", :title => "View Dashboard" %></li>
  <li><%= link_to 'Artists', artists_path, :class => "fa fa-microphone", :id => "button", :title => "View Artists"  %></li>
  <li><%= link_to 'Genres', genres_path, :class => "fa fa-th", :id => "button", :title => "View Genres"  %></li>
  <li><%= link_to 'Albums', albums_path, :class => "fa fa-music", :id => "button", :title => "View Albums"  %></li>
  <li><%= link_to 'Users', users_path, :class => "fa fa-users", :id => "button", :title => "View Users"  %></li>
  <li><%= link_to 'Orders', orders_path, :class => "fa fa-cart-arrow-down", :id => "button", :title => "View Orders"  %></li>
</ul>
<div style="clear:both;"></div>

<h1>Listing All Albums</h1>
<p id="notice"><%= notice %></p>

<%= link_to 'New Album', new_album_path, :class => "fa fa-plus", :id => "button", :title => "New Album" %>
<div id="no-more-tables">
  <table>
    <thead>
      <tr>
        <th class="numeric">Name</th>
        <th class="numeric">Featured</th>
        <th class="numeric">Price</th>
        <th class="numeric">Year</th>
        <th class="numeric" colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @albums.each do |album| %>
        <tr>
          <td data-title="Name" class="numeric"><%= album.name %></td>
          <td data-title="Featured" class="numeric"><%= album.featured %></td>
          <td data-title="Price" class="numeric"><%= album.price %></td>
          <td data-title="Year" class="numeric"><%= album.year %></td>
          <td class="numeric"><%= link_to 'View', album, :class => "fa fa-eye", :id => "button", :title => "View Album" %></td>
          <td class="numeric"><%= link_to 'Edit', edit_album_path(album), :class => "fa fa-pencil", :id => "button", :title => "Edit Album"  %></td>
          <td class="numeric"><%= link_to 'Delete', album, method: :delete, data: { confirm: 'Are you sure?' }, :class => "fa fa-trash-o", :id => "button", :title => "Delete Album"  %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<br>

<%= link_to 'New Album', new_album_path, :class => "fa fa-plus", :id => "button", :title => "New Album" %>
</div>

app/views/albums/new.html.erb
<div class="admin new-album inner">
  <h1>Add a New Album</h1>
  <p><%= link_to "Dashboard", admin_path %></p>
  <%= render 'form' %>
  <%= link_to 'Back', albums_path %>
</div>

app/views/albums/show.html.erb
<div class="admin album-show inner">
  <p id="notice"><%= notice %></p>
      <%= render partial: 'album',
                               object: @album,
                               locals: {homepage: false, album_listings: false,order_item: @order_item }%>
  <%= link_to 'Edit', edit_album_path(@album) %> |
  <%= link_to 'Back', albums_path %>
</div>